### PR TITLE
Rd/feat/send mail summary

### LINKED ISSUE #80: On bubble deletion, send meeting summary by mail
Depends on #75

### PR DESCRIPTION
**Pull request by Augustin68**
Close #80

### CODE REVIEW

**Comment by Augustin68** [comment]
The rainbow end of bubble event do not trigger. 
Investigating...

**Comment by Augustin68** [comment]
Everything work except the function getBubbleMessages() in rainbow service. 
If @samymsa or @Bricklou can check, it's with pleasure !!

**Comment by samymsa** [comment]
Meeting summary is currently sent on meeting end. Maybe we should do it on bubble clean, but not sure if bubble cleaning is working.

**Comment by Augustin68** [comment]
> Meeting summary is currently sent on meeting end. Maybe we should do it on bubble clean, but not sure if bubble cleaning is working.

At the begining we were doing at the same time as the bubble cleaning. But, it was a bit of a mistake because the bubble was cleaned before we get back all the messages. So I changed it to bubble end event to avoid this issue

**Pull request merged**
